# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8b625c7febdbbf0c3425b0973bec1492f3d3f4678a8a94027fd12926d62ae4e9233c51421358c88db8875017e87e90fa02a8be52d96d96f03fc908735115e9b0

test:
  secret_key_base: 160b4c96ed1e5d2d3196a3a22f4343cb197e2419e0ed80839a39c5c61fbd371d31ca9937739b4ec4005f4008a375129f6d7917f1630ed3e77626b5096285959f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
